#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pypsrp
Version  : 0.7.0
Release  : 3
URL      : https://files.pythonhosted.org/packages/a9/82/d6ecba6d223bebbfb3dec02b5cb9974e5dd9b8a97603452f95724526151e/pypsrp-0.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/a9/82/d6ecba6d223bebbfb3dec02b5cb9974e5dd9b8a97603452f95724526151e/pypsrp-0.7.0.tar.gz
Summary  : PowerShell Remoting Protocol and WinRM for Python
Group    : Development/Tools
License  : MIT
Requires: pypi-pypsrp-license = %{version}-%{release}
Requires: pypi-pypsrp-python = %{version}-%{release}
Requires: pypi-pypsrp-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
# pypsrp - Python PowerShell Remoting Protocol Client library
[![Test workflow](https://github.com/jborean93/pypsrp/actions/workflows/ci.yml/badge.svg)](https://github.com/jborean93/pypsrp/actions/workflows/ci.yml)
[![codecov](https://codecov.io/gh/jborean93/pypsrp/branch/master/graph/badge.svg)](https://codecov.io/gh/jborean93/pypsrp)
[![PyPI version](https://badge.fury.io/py/pypsrp.svg)](https://badge.fury.io/py/pypsrp)

%package license
Summary: license components for the pypi-pypsrp package.
Group: Default

%description license
license components for the pypi-pypsrp package.


%package python
Summary: python components for the pypi-pypsrp package.
Group: Default
Requires: pypi-pypsrp-python3 = %{version}-%{release}

%description python
python components for the pypi-pypsrp package.


%package python3
Summary: python3 components for the pypi-pypsrp package.
Group: Default
Requires: python3-core
Provides: pypi(pypsrp)
Requires: pypi(cryptography)
Requires: pypi(pyspnego)
Requires: pypi(requests)

%description python3
python3 components for the pypi-pypsrp package.


%prep
%setup -q -n pypsrp-0.7.0
cd %{_builddir}/pypsrp-0.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641941556
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pypsrp
cp %{_builddir}/pypsrp-0.7.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pypsrp/3feb94e218ec9cc73b84cf413325044398ed1ebb
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pypsrp/3feb94e218ec9cc73b84cf413325044398ed1ebb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
